DROP TABLE grant_beneficiary;

CREATE TABLE grant_beneficiary (
   grant_beneficiary_id uuid NOT NULL,
   scheme_id INT NULL,
   application_id INT NULL,
   submission_id uuid NULL,
   version BIGINT NOT NULL,
   created timestamp without time zone,
   created_by BIGINT NOT NULL,
   last_updated timestamp without time zone,
   last_updated_by BIGINT NOT NULL,
   location_ne_eng boolean NULL,
   location_nw_eng boolean NULL,
   location_se_eng boolean NULL,
   location_sw_eng boolean NULL,
   location_mid_eng boolean NULL,
   location_sco boolean NULL,
   location_wal boolean NULL,
   location_nir boolean NULL,
   has_provided_additional_answers boolean NULL,
   supports_specific_gender boolean NULL,
   supporting_gender_details VARCHAR(100) NULL,
   age_group1 boolean NULL,
   age_group2 boolean NULL,
   age_group3 boolean NULL,
   age_group4 boolean NULL,
   age_group5 boolean NULL,
   age_group_all boolean NULL,
   ethnic_group1 boolean NULL,
   ethnic_group2 boolean NULL,
   ethnic_group3 boolean NULL,
   ethnic_group4 boolean NULL,
   ethnic_group5 boolean NULL,
   ethnic_group_other boolean NULL,
   ethnic_other_details VARCHAR(100) NULL,
   ethnic_group_all boolean NULL,
   supporting_disabilities boolean NULL,
   sexual_orientation_group1 boolean NULL,
   sexual_orientation_group2 boolean NULL,
   sexual_orientation_group3 boolean NULL,
   sexual_orientation_other boolean NULL,
   sexual_orientation_other_details VARCHAR(100) NULL,
   sexual_orientation_group_all boolean NULL,
   sex_group1 boolean NULL,
   sex_group2 boolean NULL,
   sex_group_all boolean NULL,
   CONSTRAINT pk_grantbeneficiary PRIMARY KEY (grant_beneficiary_id)
);