-- TBD schemas for grant_admin, grant_organisation and their FK

CREATE TABLE template_grant_application
(
    template_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    definition json NOT NULL,
    CONSTRAINT template_grant_application_pkey PRIMARY KEY (template_id)
);


CREATE TABLE grant_scheme
(
    grant_scheme_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    funder_id integer NOT NULL,
    version integer NOT NULL,
    ggis_identifier character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    last_updated timestamp without time zone,
    last_updated_by integer,
    scheme_name character varying(255) NOT NULL,
    scheme_contact character varying(255),
    CONSTRAINT grant_scheme_pkey PRIMARY KEY (grant_scheme_id)
);

CREATE UNIQUE INDEX grant_scheme_id_version_idx ON grant_scheme (grant_scheme_id,version);


CREATE TABLE grant_application
(
    grant_application_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grant_scheme_id integer,
    version integer,
    created timestamp without time zone,
    last_update_by integer,
    last_updated timestamp without time zone,
    application_name character varying(255),
    status character varying(255) NOT NULL,
    definition json NOT NULL,
    CONSTRAINT grant_application_pkey PRIMARY KEY (grant_application_id),
    CONSTRAINT grant_scheme_fk FOREIGN KEY (grant_scheme_id)
            REFERENCES grant_scheme (grant_scheme_id) MATCH SIMPLE
            ON DELETE CASCADE
);

CREATE UNIQUE INDEX grant_application_id_version_idx ON grant_application (grant_application_id,version);
