-- grant_mandatory_questions
CREATE TABLE IF NOT EXISTS public.grant_mandatory_questions (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	grant_scheme_id int4 NOT NULL,
    submission_id uuid NULL,
	name varchar(255) NULL,
	addressLine1 varchar(255) NULL,
	addressLine2 varchar(255) NULL,
	city varchar(255) NULL,
	county varchar(255) NULL,
	postcode varchar(255) NULL,
	orgType varchar(255) NULL,
	companiesHouseNumber varchar(255) NULL,
	charityCommissionNumber varchar(255) NULL,
	fundingAmount varchar(255) NULL,
	fundingLocation varchar(255) NULL,
    status varchar(255) NULL,
    version int4 NOT NULL,
	created timestamp NOT NULL,
	created_by BIGINT NOT NULL,
    last_updated timestamp NOT NULL,
	last_updated_by BIGINT NOT NULL,
	CONSTRAINT grant_mandatory_questions_pkey PRIMARY KEY (id)
);


-- grant_mandatory_questions foreign keys

ALTER TABLE public.grant_mandatory_questions
ADD CONSTRAINT grant_mandatory_questions_grant_scheme_id_to_grant_scheme_table_fk
FOREIGN KEY (grant_scheme_id)
REFERENCES public.grant_scheme(grant_scheme_id)
MATCH simple
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE public.grant_mandatory_questions
ADD CONSTRAINT grant_mandatory_questions_grant_scheme_id_to_grant_submission_table_fk
FOREIGN KEY (submission_id)
REFERENCES public.grant_submission(id)
MATCH simple
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE public.grant_mandatory_questions
ADD CONSTRAINT grant_mandatory_questions_created_by_to_grant_applicant_table_fk
FOREIGN KEY (created_by)
REFERENCES public.grant_applicant(id)
MATCH simple
ON DELETE CASCADE
ON UPDATE NO ACTION;

ALTER TABLE public.grant_mandatory_questions
ADD CONSTRAINT grant_mandatory_questions_last_updated_by_to_grant_applicant_table_fk
FOREIGN KEY (last_updated_by)
REFERENCES public.grant_applicant(id)
MATCH simple
ON DELETE CASCADE
ON UPDATE NO ACTION;