ALTER TABLE GRANT_SCHEME ADD CREATED_BY integer NOT NULL,
    ADD CONSTRAINT FK_GRANT_ADMIN_ID_GRANT_ADMIN
FOREIGN KEY (CREATED_BY) REFERENCES PUBLIC.GRANT_ADMIN (GRANT_ADMIN_ID) ON
UPDATE NO ACTION ON
DELETE NO ACTION;


ALTER TABLE GRANT_APPLICATION ADD CREATED_BY integer NOT NULL,
    ADD CONSTRAINT FK_GRANT_ADMIN_ID_GRANT_ADMIN
FOREIGN KEY (CREATED_BY) REFERENCES PUBLIC.GRANT_ADMIN (GRANT_ADMIN_ID) ON
UPDATE NO ACTION ON
DELETE NO ACTION;
 
